---
application:
  name: rosenbridge
  version: 0.0.0

auth:
  cluster_username: dev
  cluster_password: dev

http_server:
  addr: 0.0.0.0:8080
  discovery_addr: 0.0.0.0:8080
  discovery_protocol: http

logger:
  level: info

mongo:
  addr: mongodb://dev:dev@localhost:27017/?retryWrites=true&w=majority
  database_name: rosenbridge
  operation_timeout_sec: 60
