---
application:
  name: rosenbridge
  version: 0.0.0
  solo_mode: false

auth:
  internal_username: dev
  internal_password: dev

bridges:
  max_bridge_limit: 10000
  max_bridge_limit_per_client: 10

http_server:
  addr: 0.0.0.0:8080
  discovery_addr: http://0.0.0.0:8080

logger:
  level: info

mongo:
  addr: mongodb://dev:dev@localhost:27017/?retryWrites=true&w=majority
  database_name: rosenbridge
  operation_timeout_sec: 60
