---
application:
  name: rosenbridge-1
  version: 0.0.0

auth:
  internal_username: dev
  internal_password: dev

bridges:
  max_bridge_limit: 10000
  max_bridge_limit_per_client: 10

discovery:
  discovery_addr: http://0.0.0.0:8080
  max_addr_resolution_attempts: 10
  addr_resolution_period_sec: 3

http_server:
  addr: 0.0.0.0:8080

logger:
  level: info

mongo:
  addr: mongodb://dev:dev@localhost:27017/?retryWrites=true&w=majority
  database_name: rosenbridge
  operation_timeout_sec: 60
